### ISSUE TITLE
Interested in Crowd chart?

### ISSUE THREAD

**Issue by pathob** [atlassian-labs/data-center-helm-charts#100]
Hey guys,

we need a Crowd chart, are currently working on it and would be interested in upstreaming it. The initial version my colleages created is based on your Confluence chart. Any chances to get this merged if we create a pull request?

Thanks,
Patrick

**Comment by pathob** [comment]
@dylanrathbone @wkritzinger-atlassian @pbruski @nanux @bordenit

Any opinion in this?

**Comment by nanux** [comment]
Sorry @pathob for the delay. We are considering adding the support for Crowd helm chart in future we just made a decision to not include it in the initial scope. I believe we can include the contribution but the main consideration here is that we need to make clear that it is in Atlassian cannot officially support customers using it. Providing official support means additional activities we will need on our side (onboarding support engineers, testlabs etc.) so if we leave the crowd helm chart in alpha version I think it can be included in the repository.

Can you please raise the PR?

**Comment by pathob** [comment]
Thank you @nanux , my colleague Louis created the PR now: https://github.com/atlassian-labs/data-center-helm-charts/pull/106
