### ISSUE TITLE
Ingress Cleanup

### ISSUE THREAD

**Issue by bordenit** [atlassian-labs/data-center-helm-charts#180]
The ingress could be cleaned up in the following ways:
1. The path in the ingress could be automatically defaulted to the jira.service.contextpath.
2.  The ATL_PROXY_PORT and ATL_PROXY_NAME could perhaps be added in the statefulset, where ATL_PROXY_PORT defaults to 443 and ATL_PROXY_NAME defaults to the ingress.host value.

I noticed in the server.xml the proxyPort and proxyName are empty with the standard values.yaml implementation currently.

**Comment by bianchi2** [comment]
@bordenit thanks for your comment. We do set proxy [here](https://github.com/atlassian-labs/data-center-helm-charts/blob/master/src/main/charts/bitbucket/templates/statefulset.yaml#L102) for Bitbucket but indeed, not for Jira.
@nanux did we miss it?

As to ingress - a totally valid request

**Comment by nanux** [comment]
I think this is worth investigating, I will put it in our backlog.

**Comment by nanux** [comment]
This should be fixed now with merged #202. @bordenit could you please test it?
