### ISSUE TITLE
False warning on missing volumes

### ISSUE THREAD

**Issue by bianchi2** [atlassian-labs/data-center-helm-charts#190]
With `volumes.localHome.persistentVolumeClaim.create: true` and `volumes.sharedHome.persistentVolumeClaim.create: false` but volumes.sharedHome.persistentVolumeClaim.claimName: jira-shared-home` getting this warning:

```
#################################################################################
######              WARNING: Persistent volume is not used!!!               #####
######            Data will be lost when the pod is terminated.             #####
#################################################################################
```
which isn't true since both local and shared home are persisted. I just don't let Helm create shared home PVC and pre-created it myself wit the right storage class and annotations.

**Comment by yzha645** [comment]
Hi Eugene, 

I just tested using the same configuration as you did, the warning is not showing up.. 

For sharedHome pvc name, did you put it into `volumes.sharedHome.persistentVolumeClaim.claimName` as you mentioned above, or `volumes.sharedHome.customVolume.persistentVolumeClaim.claimName`? When `volumes.sharedHome.persistentVolumeClaim.create` is set to false, `customVolume` is the place to hold the pre-created pvc. If you did put it in the later location, do you mind providing the values.yaml file? 

And in terms of this warning, it is specific for shared home. I'll make the wording more precise. 

Cheers

**Comment by bianchi2** [comment]
@yzha645 my bad. It has to be a customVolume which makes sense :) 

```
{{- define "jira.volumes.sharedHome" -}}
- name: shared-home
{{- if .Values.volumes.sharedHome.persistentVolumeClaim.create }}
  persistentVolumeClaim:
    claimName: {{ include "jira.fullname" . }}-shared-home
{{ else }}
{{ if .Values.volumes.sharedHome.customVolume }}
{{- toYaml .Values.volumes.sharedHome.customVolume | nindent 2 }}
{{ else }}
  emptyDir: {}
{{- end }}
{{- end }}
```
