### ISSUE TITLE
Session Affinity Recommendation

### ISSUE THREAD

**Issue by bordenit** [atlassian-labs/data-center-helm-charts#204]
If you are to do load testing of this configuration perhaps consider setting the SessionAffinity in the service to clusterIP. For some reason even with the Session Affinity on the ingress, the backend node will switch on users and then they will have issues with their sessions.

https://kubernetes.io/docs/concepts/services-networking/service/#proxy-mode-userspace

A use case I have experienced:
Log out of Jira and sit at the logout page for 3 minutes. Click the "Log in again" button and see if (a.) the node at the bottom of the page switches, or (b.) you get a login error due your x-ausername switching to "anonymous" (usually related to the node switching) and maybe that node knows nothing about you? Setting this affinity in the service seems to result in less errors with this use case. Perhaps you will have similar results.

"If you want to make sure that connections from a particular client are passed to the same Pod each time, you can select the session affinity based on the client's IP addresses by setting service.spec.sessionAffinity to "ClientIP" (the default is "None"). You can also set the maximum session sticky time by setting service.spec.sessionAffinityConfig.clientIP.timeoutSeconds appropriately. (the default value is 10800, which works out to be 3 hours)."

**Comment by bianchi2** [comment]
@bordenit thanks for your comment. It does make sense. Which ingress controller did you use when having issues of sticky cookie not working, i.e. requests being send to a random service backend?

**Comment by bordenit** [comment]
@bianchi2 Nginx ingress-controller. I used the configuration available here in the helm chart.

**Comment by nanux** [comment]
Hi @bordenit, what issues are you experiencing?

If you are using the out-of-the-box Ingress objects, they have `affinity` annotation for nginx ingress-controller:
For example:
https://github.com/atlassian-labs/data-center-helm-charts/blob/master/src/main/charts/jira/templates/ingress.yaml#L11

The `SessionAffinity` property described in [k8s docs](https://kubernetes.io/docs/concepts/services-networking/service/#proxy-mode-userspace) is for the pod -> pod communication. It means if Jira node 1 wants to talk with another Jira node, it will try to use always the same node. We haven't tested that option as we have requirements only on ingress session affinity.

Could you provide more detail, why the `SessionAffinity` should be included and what problem is it solving?

Thank you

**Comment by bianchi2** [comment]
Sticky cookie from Nginx ingress should be enough to always forward requests to the same backend pod. I haven't experienced any issues with it, though, of course, I never did some extensive testing with hundreds of requests. My understanding is that once a cookie is set in a browser, requests will go to the same replica of a StatefulSet, provided that this replica exists. And this is what I see in my lab environment (also Nginx ingress controller)

**Comment by bordenit** [comment]
@nanux We have session affinity set at AWS NLB, using the session cookie and persistent setting with nginx ingress controller, and then set this ClientIP on the service as well. We have a couple hundred users. I plan to try this ClientIP setting anyway during our next update to see what happens. We have no issues when only using 1 pod, but in engineering this setting seemed like an improvement. I’ll close this issue, since you can’t replicate at this time.

**Comment by nanux** [comment]
Thank you @bordenit. Please let us know if you have additional findings after your next update.
