### ISSUE TITLE
Unable to create directory for deployment

### ISSUE THREAD

**Issue by Forbzy** [atlassian-labs/data-center-helm-charts#240]
Below is the error log.
`14-Aug-2021 13:32:21.183 SEVERE [Catalina-startStop-1] org.apache.catalina.startup.HostConfig.beforeStart Unable to create directory for deployment: [/opt/atlassian/jira/conf/Catalina/localhost]`

I found the solution in your documentation found in the below link. 
https://confluence.atlassian.com/jirakb/jira-server-throws-unable-to-create-directory-for-deployment-error-on-startup-389781040.html

Your chart doesn't make it easy to implement the solution. I think just running the below command is enough.
`chown -R jira:jira /opt/atlassian/jira/conf/Catalina/localhost`

How to reproduce.
1. Helm install

Can you make the chart more flexible please?

**Comment by errcode1202** [comment]
@Forbzy thanks for raising this. There is an existing [ticket](https://jira.atlassian.com/browse/SCALE-46) to address this problem and its on the backlog to be fixed. This error shouldn't prevent the container from starting up though (false positive) and can be ignored.

**Comment by Forbzy** [comment]
Ok thanks for letting me know. Will close issue.
