### ISSUE TITLE
Managed Synchrony in Confluence

### ISSUE THREAD

**Issue by Boojapho** [atlassian-labs/data-center-helm-charts#81]
Currently, you have two options for Synchrony in the Confluence helm chart:
1) Deploy with Synchrony disabled, which sets `-Dsynchrony.btf.disabled=true`
2) Or deploy with Synchrony enabled, which deploys a Statefulset, Service, entry point, etc. for a stand-alone Synchrony

I would like to add another option to provide a [Synchrony managed by Confluence](https://confluence.atlassian.com/doc/set-up-a-synchrony-cluster-for-confluence-data-center-958779073.html).

To do this, I would add a "synchrony.managed" boolean to the values.  If managed is set to false (and synchrony.enabled is true), it deploys the stand-alone Synchrony.  If managed is set to true (and synchrony.enabled is true).  It would deploy the following:
- Same service as stand-alone
- JVM option of `-Dsynchron.btf.disabled=false`
- Additional exposed ports on the Confluence stateful set for Synchrony's service port and Hazelcast port.  This will require a port name change to avoid conflicts.
- Additional labels added to stateful set for Confluence so service will select it

**Comment by Boojapho** [comment]
I have a branch on my local machines with the changes for review.   I don't have permission to push a new branch to the repo.  Can you grant me access so I can push the code and start a pull request?

**Comment by Boojapho** [comment]
Pull Request: #82

**Comment by nanux** [comment]
Hi @Boojapho, as discussed in detail in the PR #82, we are not planning to add this to the current stage. Running 2 separate JVM processes is not good practice in Kubernetes and we've run previously into issues to make it work on different platforms.
