### ISSUE TITLE
Can we use the helm chart for production setup?

### ISSUE THREAD

**Issue by pbagewadi-athene** [atlassian-labs/data-center-helm-charts#84]
Hi Team,
We are planning to setup Jira and Confluence on AWS EKS, as per the readme file, the charts are experimental and unsupported but the version 0.5.0 has verified check. So can we use this version to setup apps on AWS EKS production?

**Comment by bianchi2** [comment]
@pbagewadi-athene there's no official support until it's announced. You may deploy charts and we'd appreciate feedback (and PRs :) ) however, there's no official support yet.

**Comment by pbagewadi-athene** [comment]
@bianchi2 any ETA on date when it may be released and officially supported? We are planning to move to datacenter on AWS EKS cluster in April-May. As of now, I am facing login issues and opened https://github.com/atlassian-labs/data-center-helm-charts/issues/88.

**Comment by nanux** [comment]
Hi @pbagewadi-athene, sorry for the late response. The Kubernetes support for DC products is on the official roadmap slated for Q4 this year - https://www.atlassian.com/roadmap/data-center?&search=kubernetes
