### ISSUE TITLE
Login infinite loop if there is more than 1 pod [istio]

### ISSUE THREAD

**Issue by pbagewadi-athene** [atlassian-labs/data-center-helm-charts#88]
@kennymacleod @bkwiatek-atlassian ,
I am facing login issues when I scale the pods to >1. This works when there is only one pod.
I found the resolution in Atlassian docs.
But how can I incorporate the change in helm through values.yaml ? 

Resolution is to add JVM_EXTRA_ARGS (-DjvmRoute=respective node id) in setenv.sh

Resolution
Verify that node name(s) are consistent across the configuration elements. You will need to have the same node name defined in:

<JIRA-HOME>/cluster.properties file at jira.node.id
**<JIRA-INSTALL>/bin/setenv.sh under JVM_EXTRA_ARGS (-DjvmRoute=)**
In your load balancer configuration (example for Apache: BalancerMember http://<host>:<ip> route=nodename)

https://confluence.atlassian.com/jirakb/keep-being-redirected-to-the-login-page-after-providing-the-right-credentials-on-jira-data-center-610435649.html

**Comment by bianchi2** [comment]
@pbagewadi-athene the fix is implemented, though I am not sure it's available in the public tags now. Also, your ingress need to have session affinity annotations. Which ingress controller do you use?

**Comment by pbagewadi-athene** [comment]
@bianchi2 We are using Istio. Currently I see 0.5.0 tag is available. Could you guild me on how to resolve or let me know when it will be released ?

**Comment by bianchi2** [comment]
@nanux do you happen to know if the fix with overwriting clusterID in cluster.properties in Jira is available in the public tags on DockerHub now? If so, which version?

**Comment by pbagewadi-athene** [comment]
@bianchi2 @nanux @kennymacleod @bkwiatek-atlassian 
Any idea when it will be released for use?

**Comment by bianchi2** [comment]
@nanux yes that. Of course, my question makes sense only if the KB correctly explains what causes the error. @pbagewadi-athene what is your Jira image tag?

**Comment by pbagewadi-athene** [comment]
We are using atlassian/jira-software:8.11.1-ubuntu-jdk11.
with latest helm release, login issue is resolved for > 1 instance. but unable to create any issue/tickets, meaning the issue does not get saved. with one instance(pod) works fine.

**Comment by bianchi2** [comment]
@pbagewadi-athene what particular error do you see? Sharing a screenshot and logs will certainly help.

**Comment by pbagewadi-athene** [comment]
1st I thought the issue was with creating tickets, but the issue is still same, I am unable to login back if I create 2 instance.
kubectl scale sts jira --replicas=2

the login page keep on coming back like in loop and does not log me in.
I am using latest helm jira version: 0.11.0 release.

**Comment by pbagewadi-athene** [comment]
so basically, it keep on being redirected to login page if we scale up the jira instance.

**Comment by bianchi2** [comment]
@pbagewadi-athene i guess istio is to blame here. I don't think charts were tested with istio ingress gateway and/or mutual tls. Most likely, the second node never joins the cluster, while your requests land on this new pod. Do you see anything suspicious in logs (both pods)?

**Comment by pbagewadi-athene** [comment]
Let me check on this and get back on this.
Thank you.

**Comment by pbagewadi-athene** [comment]
Which all session affinity needs to be added for istio? Could you please help me to list out.
I have added cookie and now it is sending details to only that pod to which it makes connections at first for that user session and now login issues are resolved. But I am worried how the load will be handled in this case if all(majority) users get connected to same pod.

**Comment by bianchi2** [comment]
Hi @pbagewadi-athene I don't have a lot of istio experience but usually sticky cookies work the same way - an ingress controller (istio in your case) adds a cookie and requests are sent to the same pod. If you make a request in an incognito tab odds are that your request goes to a different backend pod. The same will happen to your users, so you should expect requests to be evenly spread between Jira pods. Also, you can normally set max age for this cookie, at least your can do so with Nginx ingress controller.

Did adding session affinity in isto fix the issue? Do you see two nodes in Jira admin page - clustering?

**Comment by pbagewadi-athene** [comment]
Yes, after adding sticky cookie the main issue of logging is resolved as the requests are sent to the same pod for a specific user. I see pods in clustering and also tried with incognito and that works just fine.

I will do more testing and share the results. but for now on high level, everything works just fine.

**Comment by bianchi2** [comment]
@pbagewadi-athene awesome! We do mention session affinity aka sticky cookies [here](https://github.com/atlassian-labs/data-center-helm-charts/blob/365e096f0dd9edc253cf9bbae737e3651de51a38/docs/CONFIGURATION.md#ingress). Different ingress controllers have different ways to enable and configure those.

**Comment by nanux** [comment]
@pbagewadi-athene, thanks for the update! I will close the ticket now but if you have some guide on how to set it up in an Istio environment, feel free to add it to the ticket, so it can help somebody else as well.
